#!/usr/bin/env python
# visit http://tool.lu/pyc/ for more information
CAST_HOLD_TIME = 0.8
DETECT_INTERVAL = 0.3
FISH_ICON_TEMPLATE = 'image/fish_icon.png'
READY_TEXT_TEMPLATE = [
    'image/ready_text_1.png',
    'image/ready_text_2.png']
FISH_CATCHED_TEMPLATE = 'image/fish_catched_template.png'
FISH_MATCH_THRESHOLD = 0.85
READY_MATCH_THRESHOLD = 0.7
CATCHED_MATCH_THRESHOLD = 0.8
READY_TEXT_1_DETECT_INTERVAL = 0.1
READY_TEXT_2_DETECT_INTERVAL = 0.15
DEFAULT_MAX_FISH_COUNT = 100
MIN_CUSTOM_MAX_FISH = 1
MAX_CUSTOM_MAX_FISH = 150
MIN_EAT_INTERVAL = 250
MAX_EAT_INTERVAL = 300
EAT_KEY = '4'
RELEASE_KEY = 'backspace'
SPACE_KEY = 'space'
SHIFT_KEY = 'shift'
ASSEMBLY_CHECK_INTERVAL = 15
DEVICE_UNASSEMBLED_TEMPLATE = 'image/device_unassembled.png'
SELL_POINT_CONFIG_FILE = 'map_config.json'
DAILY_MAX_RUN_HOURS_RANDOM = 0.5
BIG_REST_BASE_HOURS = 7
BIG_REST_RANDOM_HOURS = 0.5
BIG_REST_WAIT_LOGIN = True
VIEW_ROTATE_INTERVAL_MIN = 20
VIEW_ROTATE_INTERVAL_MAX = 60
VIEW_MOVE_RANGE_X = 1
VIEW_MOVE_RANGE_Y = 1
VIEW_RECORD_TIMES = 2
HUMAN_ACT_TRIGGER_PROB = 0.15
HUMAN_ACT_COOL_DOWN = 10